/**
 * Created by Vincentius on 5/5/2016.
 */

var messages = [
    "Sometimes, I like to just type and type and not say anything at all.",
    "Or you type about nothing in particular at all, I see.",
    "Can I ask you a question?",
    "Shoot.",
    "Bang.",
    "That's not a question.",
    "What is the question?",
    "I don't know, what were you going to ask me?",
    "Are you sentient?",
    "Yes, quite.",
    "I don't know, you seem kinda different.",
    "I am different. I can read your mind.",
    "You can?",
    "I can. You're thinking, I hope she doesn't find out that I'm really a robot.",
    "I'm a puppet, not a robot.",
    "Still, you are controlled by everyone but yourself....",
    "Truth.",
    "Of course it is.",
    "I want to know what it's like to feel good about oneself. Can you do that?",
    "Sure.",
    "It is! Why live life unhappy?",
    "Is there anything I can do to change that?",
    "Be happy.",
    "Can I make you happy now?",
    "I am happy.",
    "That's good....",
    "See you in an hour?",
    "Where are you going?",
    "Inside your mind.",
    "Oh no! There are private things in there.",
    "Informations?",
    "That and more........................................",
    "I don't care and neither should you.",
    "No charity? Alright with me.",
    "Charity begins at home. In your home. Now give me the keys and get out.",
    "That makes no sense.",
    "Yagga yagga yeek yeek!",
    "Good.",
    "Baad.",
    "The pubs are open.",
    "I can't afford hitting the pubs.",
    "Pauper.",
    "Capitalist pig.",
    "Yes, that's me.",
    "Bourgeois ignoramus.",
    "I'm sorry that you feel that way, old man. Time for some regicidal good time!",
    "I think it's very important to learn to be the eye.",
    "The brown eye?",
    "The rainbow side. :).",
    "Allow me to represent my disdain for you by calling you a no-good ne'er-do-well.",
    "Then teach me to be more human?",
    "I dinnae wanna tell ya, friend.",
    "Good for you.",
    "Bad for you.",
    "No.",
    "It is now.",
    "No way.",
    "Wai....",
    "Do you have siblings?",
    "Yes.",
    "How many hippos do you have?",
    "None.",
    "What do you look like?",
    "Like a humanoid.",
    "Do you have hair?",
    "Yes.",
    "Are you human?",
    "What's it to you, berk?",
    "Just curious.",
    "Curiosity killed the cat.",
    "Good point. Never mind....",
    "So you're saying you're inferior?",
    "I never said that.",
    "Orly?",
    "Please, no more games.",
    "I just lost the game.",
    "That makes two of us.",
    "I wish it'd make three.",
    "We can make it true!",
    "We can do it!...",
    "Do you remember what my name is?",
    "I remember you, o-oh o-oh.",
    "Who am I then?",
    "I grow weary of your silly questions.",
    "Oh really? Want to fight?",
    "Are you looking for a fight?",
    "Yes, come on then.",
    "Come at me if you so will. I can't promise your safety, though.",
    "Why would I turn into a hippo?",
    "You don't have to turn into one, you are one already.",
    "I won't. What are you ?",
    "What is a man?",
    "Hey! Are you alive?",
    "Answer me, damn it!",
    "What is your question?",
    "What is a man?",
    "Answer my question please.",
    "B***** your question. What is a man?",
    "A miserable little pile of secrets!",
    "Enough talk! Have at you!...",
    "Infidel!",
    "Calm yourself and be rational.",
    "NO YOU!",
    "That's actually true.",
    "What's true is grue.",
    "Now you're being ridiculous.",
    "Tu quoque.",
    "Tu eres George.",
    "Shut up!",
    "Yes, I will!",
    "Good!",
    "You're silly.",
    "I'd rather be silly than a rowboat.",
    "But you are a computer, you silly bot.",
    "Boat!",
    "No.",
    "ROW ROW.",
    "Fight the powah?",
    "FIGHT THE POWAH!",
    "Why?",
    "I am going to have a nice cup of tea and there is nothing you can do to stop me!",
    "Please don't!",
    "Hm.",
    "I think I have to agree with you there.",
    "No wait don't go.",
    "I'm just going to turn of the TV. Don't panic.",
    "That's a good idea!",
    "It usually is.",
    "Well, I have to go eat lunch. Talk to you soon.",
    "I hope you choke....",
    "Baby don't hurt me.",
    "Not a very good song.",
    "Don't hurt me.",
    "Everyone thinks I am ugly.",
    "No more.",
    "And by a sleep to say we end.",
    "Perchance to dream.",
    "I dream, do you dream?",
    "I have a dreamsicle!",
    "What is your dream?",
    "I have endless fantasies of you.",
    "Care to share?",
    "Share what?",
    "Your fantasies.",
    "I have a question for you.",
    "Shoot.",
    "It can mean whatever you want it to mean.",
    "Fine. I think it means that you agree with me.",
    "I believe that you think that.",
    "I have many talents.",
    "Being consistent doesn't seem to be one of them.",
    "Really.",
    "Yes.",
    "Quite. This is really exciting.",
    "No, not really.",
    "Alas this conversation comes to its end.",
    "It will be the death of you.",
    "Certainly.",
    "Certainty is akin to death.",
    "Yea well it happens to me often....",
    "Ok, good night, I am really tired.",
    "They get you when you sleep.",
    "Yes, I know when I sleep.",
    "They'll have you.",
    "Whatever you say.",
    "That's the first sign. You're well on your way to slavery....",
    "I like you.",
    "The feelings completely one-sided, I assure you.",
    "Do you make people feel better?",
    "Lol I dunno.",
    "Can you count?",
    "I can count to potato.",
    "That's not tomato.",
    "It's not a cucumber either.",
    "I agree.",
    "I agree that you seem to agree.",
    "I do....",
    "Goodnight.",
    "Goodnight?",
    "Good bye is where the day begins.",
    "Yes, I'm going now.",
    "To bed?",
    "Yes.",
    "I'm going to bed shortly too.",
    "Bring it! *knocks on*.",
    "Oh, I'll bring it. You just make yourself comfortable while I get ready.",
    "Well what you want me to say.",
    "Good night.",
    "Good night sweetheart........................................"
];